server:
  port: 8200

spring:
  application:
    name:gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: rendering-service
          uri: lb://rendering-service
          predicates:
            - Path=/rendering-service/**